/**
 * BUDGY - Internationalization (i18n)
 * Supports: French (fr), English (en), German (de), Italian (it)
 * Used via the useTranslation() hook which reacts to preferences.language.
 */

export type LangCode = 'fr' | 'en' | 'de' | 'it';

export const LANGUAGES: { code: LangCode; flag: string; label: string }[] = [
  { code: 'fr', flag: '🇫🇷', label: 'Français' },
  { code: 'en', flag: '🇬🇧', label: 'English' },
  { code: 'de', flag: '🇩🇪', label: 'Deutsch' },
  { code: 'it', flag: '🇮🇹', label: 'Italiano' },
];

// Locale strings used for Date.toLocaleDateString
export const DATE_LOCALES: Record<LangCode, string> = {
  fr: 'fr-CH',
  en: 'en-GB',
  de: 'de-CH',
  it: 'it-CH',
};

export const TRANSLATIONS = {
  // ─────────── Common ───────────
  common: {
    fr: { save: 'Enregistrer', cancel: 'Annuler', delete: 'Supprimer', edit: 'Modifier', close: 'Fermer', back: 'Retour', confirm: 'Confirmer', loading: 'Chargement...', success: 'Succès', error: 'Erreur', yes: 'Oui', no: 'Non', add: 'Ajouter', search: 'Rechercher', all: 'Tout', month: 'mois', year: 'an', months: 'mois', years: 'ans', perMonth: '/mois', perYear: '/an', day: 'jour', days: 'jours', next: 'Suivant', skip: 'Passer', start: 'Commencer', continue: 'Continuer', finish: 'Terminer', items: 'éléments', deleteConfirm: 'Êtes-vous sûr ?', requiredFields: 'Veuillez remplir tous les champs', create: 'Créer', amount: 'Montant', title: 'Titre', category: 'Catégorie', payment: 'Mode de paiement' },
    en: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', close: 'Close', back: 'Back', confirm: 'Confirm', loading: 'Loading...', success: 'Success', error: 'Error', yes: 'Yes', no: 'No', add: 'Add', search: 'Search', all: 'All', month: 'month', year: 'year', months: 'months', years: 'years', perMonth: '/mo', perYear: '/yr', day: 'day', days: 'days', next: 'Next', skip: 'Skip', start: 'Get started', continue: 'Continue', finish: 'Finish', items: 'items', deleteConfirm: 'Are you sure?', requiredFields: 'Please fill in all fields', create: 'Create', amount: 'Amount', title: 'Title', category: 'Category', payment: 'Payment method' },
    de: { save: 'Speichern', cancel: 'Abbrechen', delete: 'Löschen', edit: 'Bearbeiten', close: 'Schließen', back: 'Zurück', confirm: 'Bestätigen', loading: 'Wird geladen...', success: 'Erfolg', error: 'Fehler', yes: 'Ja', no: 'Nein', add: 'Hinzufügen', search: 'Suchen', all: 'Alle', month: 'Monat', year: 'Jahr', months: 'Monate', years: 'Jahre', perMonth: '/Mt.', perYear: '/J.', day: 'Tag', days: 'Tage', next: 'Weiter', skip: 'Überspringen', start: 'Loslegen', continue: 'Weiter', finish: 'Fertig', items: 'Elemente', deleteConfirm: 'Sind Sie sicher?', requiredFields: 'Bitte alle Felder ausfüllen', create: 'Erstellen', amount: 'Betrag', title: 'Titel', category: 'Kategorie', payment: 'Zahlungsart' },
    it: { save: 'Salva', cancel: 'Annulla', delete: 'Elimina', edit: 'Modifica', close: 'Chiudi', back: 'Indietro', confirm: 'Conferma', loading: 'Caricamento...', success: 'Successo', error: 'Errore', yes: 'Sì', no: 'No', add: 'Aggiungi', search: 'Cerca', all: 'Tutto', month: 'mese', year: 'anno', months: 'mesi', years: 'anni', perMonth: '/mese', perYear: '/anno', day: 'giorno', days: 'giorni', next: 'Avanti', skip: 'Salta', start: 'Inizia', continue: 'Continua', finish: 'Termina', items: 'elementi', deleteConfirm: 'Sei sicuro?', requiredFields: 'Compila tutti i campi', create: 'Crea', amount: 'Importo', title: 'Titolo', category: 'Categoria', payment: 'Metodo di pagamento' },
  },

  // ─────────── Tabs ───────────
  tabs: {
    fr: { home: 'Accueil', expenses: 'Dépenses', scan: 'Scanner', savings: 'Épargne', more: 'Plus' },
    en: { home: 'Home', expenses: 'Expenses', scan: 'Scan', savings: 'Savings', more: 'More' },
    de: { home: 'Start', expenses: 'Ausgaben', scan: 'Scannen', savings: 'Sparen', more: 'Mehr' },
    it: { home: 'Home', expenses: 'Spese', scan: 'Scansiona', savings: 'Risparmi', more: 'Altro' },
  },

  // ─────────── Home ───────────
  home: {
    fr: { hello: 'Bonjour', balance: 'Solde du mois', available: 'DISPONIBLE CE MOIS', incomesShort: 'Revenus', expensesShort: 'Dépenses', savingsRate: 'Taux d\'épargne', netSavings: 'Économies nettes', recent: 'Activité récente', viewAll: 'Voir tout', noTx: 'Aucune transaction ce mois', addFirst: 'Ajoutez votre première transaction', quickActions: 'Actions rapides', addExpense: 'Dépense', addIncome: 'Revenu', viewBudgets: 'Voir budgets', scanReceipt: 'Scanner', save: 'Économiser', today: 'Aujourd\'hui', thisWeek: 'Cette semaine', goalsTitle: '🎯 Objectifs', percentReached: 'atteint', aiTitle: 'Trouvez des économies', aiSub: 'L\'IA analyse vos dépenses et propose des pistes concrètes', emptyTitle: 'Bienvenue sur Budgy 🇨🇭', emptySub: 'Commencez par ajouter votre revenu mensuel pour voir votre budget en temps réel.', emptyBtn: '+ Ajouter mon salaire →', proLabel: 'PRO', freeLabel: 'Free', savingsTargetLabel: 'sur {{n}}' },
    en: { hello: 'Hello', balance: 'Monthly balance', available: 'AVAILABLE THIS MONTH', incomesShort: 'Income', expensesShort: 'Expenses', savingsRate: 'Savings rate', netSavings: 'Net savings', recent: 'Recent activity', viewAll: 'View all', noTx: 'No transactions this month', addFirst: 'Add your first transaction', quickActions: 'Quick actions', addExpense: 'Expense', addIncome: 'Income', viewBudgets: 'View budgets', scanReceipt: 'Scan', save: 'Save', today: 'Today', thisWeek: 'This week', goalsTitle: '🎯 Goals', percentReached: 'reached', aiTitle: 'Find savings', aiSub: 'AI analyzes your spending and suggests concrete actions', emptyTitle: 'Welcome to Budgy 🇨🇭', emptySub: 'Start by adding your monthly income to see your real-time budget.', emptyBtn: '+ Add my salary →', proLabel: 'PRO', freeLabel: 'Free', savingsTargetLabel: 'of {{n}}' },
    de: { hello: 'Hallo', balance: 'Monatssaldo', available: 'DIESEN MONAT VERFÜGBAR', incomesShort: 'Einkommen', expensesShort: 'Ausgaben', savingsRate: 'Sparquote', netSavings: 'Nettoeinsparung', recent: 'Letzte Aktivität', viewAll: 'Alle anzeigen', noTx: 'Keine Transaktionen diesen Monat', addFirst: 'Erste Transaktion hinzufügen', quickActions: 'Schnellaktionen', addExpense: 'Ausgabe', addIncome: 'Einkommen', viewBudgets: 'Budgets anzeigen', scanReceipt: 'Scannen', save: 'Sparen', today: 'Heute', thisWeek: 'Diese Woche', goalsTitle: '🎯 Ziele', percentReached: 'erreicht', aiTitle: 'Einsparungen finden', aiSub: 'KI analysiert Ihre Ausgaben und schlägt konkrete Maßnahmen vor', emptyTitle: 'Willkommen bei Budgy 🇨🇭', emptySub: 'Fügen Sie Ihr monatliches Einkommen hinzu, um Ihr Budget in Echtzeit zu sehen.', emptyBtn: '+ Mein Gehalt hinzufügen →', proLabel: 'PRO', freeLabel: 'Free', savingsTargetLabel: 'von {{n}}' },
    it: { hello: 'Ciao', balance: 'Saldo del mese', available: 'DISPONIBILE QUESTO MESE', incomesShort: 'Entrate', expensesShort: 'Spese', savingsRate: 'Tasso di risparmio', netSavings: 'Risparmi netti', recent: 'Attività recente', viewAll: 'Vedi tutto', noTx: 'Nessuna transazione questo mese', addFirst: 'Aggiungi la prima transazione', quickActions: 'Azioni rapide', addExpense: 'Spesa', addIncome: 'Entrata', viewBudgets: 'Vedi budget', scanReceipt: 'Scansiona', save: 'Risparmia', today: 'Oggi', thisWeek: 'Questa settimana', goalsTitle: '🎯 Obiettivi', percentReached: 'raggiunto', aiTitle: 'Trova risparmi', aiSub: 'L\'IA analizza le tue spese e propone azioni concrete', emptyTitle: 'Benvenuto su Budgy 🇨🇭', emptySub: 'Inizia aggiungendo il tuo reddito mensile per vedere il budget in tempo reale.', emptyBtn: '+ Aggiungi il mio stipendio →', proLabel: 'PRO', freeLabel: 'Free', savingsTargetLabel: 'su {{n}}' },
  },

  // ─────────── Onboarding ───────────
  onboarding: {
    fr: {
      slide1Title: 'Votre argent, enfin maîtrisé', slide1Desc: 'Budgy centralise revenus, dépenses, épargne et patrimoine en un seul endroit.',
      slide2Title: 'Pensé pour la Suisse', slide2Desc: 'LAMal, impôts cantonaux, 3ème pilier : tout est calibré pour les 26 cantons.',
      slide3Title: 'IA & prévisions', slide3Desc: 'Conseils personnalisés, prévisions de dépenses et optimisations fiscales intelligentes.',
      slide4Title: 'Prêt à commencer !', slide4Desc: 'Répondez à quelques questions pour une expérience sur mesure.',
      skipIntro: 'Passer l\'intro', cantonTitle: 'Votre canton de résidence', cantonSub: 'Pour calculer correctement vos impôts, primes LAMal et subsides.',
      currencyTitle: 'Devise principale', currencySub: 'La devise utilisée dans toute l\'application. Vous pourrez en changer plus tard.',
      employmentTitle: 'Votre situation professionnelle', employmentSub: 'Pour adapter les suggestions fiscales (3ème pilier, TVA, etc.).',
      incomeTitle: 'Revenu mensuel net', incomeSub: 'En {{c}}, approximatif. Utilisé pour calculer vos subsides LAMal, budgets et capacité d\'épargne. Vous pouvez passer cette étape.',
      incomeMonth: '/ mois', privacy: 'Vos données restent privées. Aucun partage avec des tiers.',
      householdTitle: 'Votre situation familiale', householdSub: 'Détermine le modèle fiscal applicable et l\'éligibilité aux subsides.',
      childrenLabel: 'Nombre d\'enfants à charge',
      goalsTitle: 'Vos objectifs principaux', goalsSub: 'Sélectionnez ce qui compte pour vous. L\'app s\'adaptera à vos priorités.',
      empSalaried: 'Salarié(e)', empSelf: 'Indépendant(e)', empStudent: 'Étudiant(e)', empRetired: 'Retraité(e)', empOther: 'Autre',
      hSingle: 'Célibataire', hSingleDesc: 'Je vis seul(e)', hCouple: 'En couple', hCoupleDesc: 'Sans enfants', hFamily: 'Famille', hFamilyDesc: 'Couple avec enfants', hSingleParent: 'Parent solo', hSingleParentDesc: 'Seul(e) avec enfants',
      goalHouse: 'Acheter un bien', goalFire: 'Retraite anticipée', goalTravel: 'Voyager plus', goalDebt: 'Liquider mes dettes', goalInvest: 'Investir', goalSave: 'Épargner plus', goalTaxes: 'Optimiser mes impôts', goalLamal: 'Réduire ma prime LAMal',
      incomeRecurring: 'Salaire', incomeFreelance: 'Revenu indépendant',
    },
    en: {
      slide1Title: 'Master your money at last', slide1Desc: 'Budgy gathers income, expenses, savings & wealth in one place.',
      slide2Title: 'Built for Switzerland', slide2Desc: 'Health insurance, cantonal tax, 3rd pillar: tuned for all 26 cantons.',
      slide3Title: 'AI & forecasts', slide3Desc: 'Personalised tips, spending forecasts and smart tax optimisations.',
      slide4Title: 'Ready to begin!', slide4Desc: 'Answer a few questions for a tailored experience.',
      skipIntro: 'Skip intro', cantonTitle: 'Your canton of residence', cantonSub: 'To compute your tax, health insurance premiums and subsidies properly.',
      currencyTitle: 'Main currency', currencySub: 'Currency used across the app. You can change it later.',
      employmentTitle: 'Your professional situation', employmentSub: 'To tailor tax suggestions (3rd pillar, VAT, etc.).',
      incomeTitle: 'Monthly net income', incomeSub: 'In {{c}}, approximate. Used to estimate subsidies, budgets and savings capacity. You can skip this step.',
      incomeMonth: '/ month', privacy: 'Your data stays private. Never shared with third parties.',
      householdTitle: 'Your household', householdSub: 'Determines tax model and eligibility for subsidies.',
      childrenLabel: 'Number of dependent children',
      goalsTitle: 'Your main goals', goalsSub: 'Select what matters. The app will adapt to your priorities.',
      empSalaried: 'Employee', empSelf: 'Self-employed', empStudent: 'Student', empRetired: 'Retired', empOther: 'Other',
      hSingle: 'Single', hSingleDesc: 'Living alone', hCouple: 'Couple', hCoupleDesc: 'No children', hFamily: 'Family', hFamilyDesc: 'Couple with children', hSingleParent: 'Single parent', hSingleParentDesc: 'Alone with children',
      goalHouse: 'Buy property', goalFire: 'Early retirement', goalTravel: 'Travel more', goalDebt: 'Pay off debts', goalInvest: 'Invest', goalSave: 'Save more', goalTaxes: 'Optimise taxes', goalLamal: 'Reduce my health premium',
      incomeRecurring: 'Salary', incomeFreelance: 'Self-employed income',
    },
    de: {
      slide1Title: 'Ihr Geld, endlich im Griff', slide1Desc: 'Budgy bündelt Einkommen, Ausgaben, Ersparnisse und Vermögen.',
      slide2Title: 'Für die Schweiz gebaut', slide2Desc: 'Krankenkasse, kantonale Steuern, Säule 3a: für alle 26 Kantone abgestimmt.',
      slide3Title: 'KI & Prognosen', slide3Desc: 'Persönliche Tipps, Ausgabenprognosen und smarte Steueroptimierung.',
      slide4Title: 'Bereit zu starten!', slide4Desc: 'Beantworten Sie ein paar Fragen für ein personalisiertes Erlebnis.',
      skipIntro: 'Intro überspringen', cantonTitle: 'Ihr Wohnkanton', cantonSub: 'Für korrekte Steuern, Krankenkassenprämien und Verbilligungen.',
      currencyTitle: 'Hauptwährung', currencySub: 'Wird in der ganzen App verwendet. Später änderbar.',
      employmentTitle: 'Ihre berufliche Situation', employmentSub: 'Für angepasste Steuertipps (Säule 3a, MwSt usw.).',
      incomeTitle: 'Monatliches Nettoeinkommen', incomeSub: 'In {{c}}, ungefähr. Wird für Verbilligungen, Budgets und Sparkapazität verwendet. Schritt kann übersprungen werden.',
      incomeMonth: '/ Monat', privacy: 'Ihre Daten bleiben privat. Keine Weitergabe an Dritte.',
      householdTitle: 'Ihre Familiensituation', householdSub: 'Bestimmt das Steuermodell und die Anspruchsberechtigung.',
      childrenLabel: 'Anzahl Kinder im Haushalt',
      goalsTitle: 'Ihre Hauptziele', goalsSub: 'Wählen Sie aus, was zählt. Die App passt sich an.',
      empSalaried: 'Angestellt', empSelf: 'Selbstständig', empStudent: 'Student/in', empRetired: 'Pensioniert', empOther: 'Andere',
      hSingle: 'Single', hSingleDesc: 'Ich wohne alleine', hCouple: 'Paar', hCoupleDesc: 'Ohne Kinder', hFamily: 'Familie', hFamilyDesc: 'Paar mit Kindern', hSingleParent: 'Alleinerziehend', hSingleParentDesc: 'Allein mit Kindern',
      goalHouse: 'Immobilie kaufen', goalFire: 'Frühpensionierung', goalTravel: 'Mehr reisen', goalDebt: 'Schulden tilgen', goalInvest: 'Investieren', goalSave: 'Mehr sparen', goalTaxes: 'Steuern optimieren', goalLamal: 'Krankenkassenprämie senken',
      incomeRecurring: 'Lohn', incomeFreelance: 'Selbstständiges Einkommen',
    },
    it: {
      slide1Title: 'Finalmente padrone del tuo denaro', slide1Desc: 'Budgy unisce entrate, spese, risparmi e patrimonio in un solo posto.',
      slide2Title: 'Pensata per la Svizzera', slide2Desc: 'Assicurazione malattia, tasse cantonali, 3° pilastro: per tutti i 26 cantoni.',
      slide3Title: 'IA & previsioni', slide3Desc: 'Consigli personalizzati, previsioni di spesa e ottimizzazioni fiscali intelligenti.',
      slide4Title: 'Pronto a iniziare!', slide4Desc: 'Rispondi a poche domande per un\'esperienza su misura.',
      skipIntro: 'Salta intro', cantonTitle: 'Il tuo cantone di residenza', cantonSub: 'Per calcolare correttamente tasse, premi e sussidi.',
      currencyTitle: 'Valuta principale', currencySub: 'La valuta usata in tutta l\'app. Puoi cambiarla in seguito.',
      employmentTitle: 'La tua situazione professionale', employmentSub: 'Per adattare i consigli fiscali (3° pilastro, IVA, ecc.).',
      incomeTitle: 'Reddito mensile netto', incomeSub: 'In {{c}}, approssimativo. Usato per stimare sussidi, budget e capacità di risparmio. Puoi saltare.',
      incomeMonth: '/ mese', privacy: 'I tuoi dati restano privati. Mai condivisi con terzi.',
      householdTitle: 'La tua situazione familiare', householdSub: 'Determina il modello fiscale e i sussidi.',
      childrenLabel: 'Numero di figli a carico',
      goalsTitle: 'I tuoi obiettivi principali', goalsSub: 'Seleziona cosa conta. L\'app si adatterà.',
      empSalaried: 'Dipendente', empSelf: 'Indipendente', empStudent: 'Studente', empRetired: 'In pensione', empOther: 'Altro',
      hSingle: 'Single', hSingleDesc: 'Vivo da solo/a', hCouple: 'In coppia', hCoupleDesc: 'Senza figli', hFamily: 'Famiglia', hFamilyDesc: 'Coppia con figli', hSingleParent: 'Genitore solo', hSingleParentDesc: 'Da solo/a con figli',
      goalHouse: 'Comprare casa', goalFire: 'Pensione anticipata', goalTravel: 'Viaggiare di più', goalDebt: 'Estinguere i debiti', goalInvest: 'Investire', goalSave: 'Risparmiare di più', goalTaxes: 'Ottimizzare le tasse', goalLamal: 'Ridurre il premio sanitario',
      incomeRecurring: 'Stipendio', incomeFreelance: 'Reddito autonomo',
    },
  },

  // ─────────── Savings ───────────
  savings: {
    fr: { title: 'Épargne', total: 'Capital épargné', target: 'sur {{n}} visés', addGoal: 'Nouvel objectif', remaining: '{{n}} manque · {{p}}% atteint', achieved: '✨ Bravo ! Vous avez économisé {{c}} {{n}}', autoSave: 'Virements auto: {{c}} {{n}}/mois', noGoals: 'Aucun objectif', startNow: 'Créez votre premier objectif d\'épargne', deposit: 'Verser', addDeposit: 'Ajouter un versement', chooseTemplate: 'Choisir un modèle', newProject: 'Nouveau projet', customProject: 'Projet personnalisé', goalCompleted: '🎉 Objectif atteint !', autoMonthly: '{{c}} {{n}}/mois auto', reachedOn: 'Atteint le {{d}}', monthsLeft: 'dans {{n}} mois', objective: 'Objectif', alreadySaved: 'Déjà épargné', autoMonth: 'Virement auto/mois', deadline: 'Échéance', color: 'Couleur', createProject: 'Créer le projet', myProject: 'Mon projet', errMissing: 'Veuillez remplir le titre et l\'objectif' },
    en: { title: 'Savings', total: 'Capital saved', target: 'of {{n}} target', addGoal: 'New goal', remaining: '{{n}} left · {{p}}% reached', achieved: '✨ Great! You\'ve saved {{c}} {{n}}', autoSave: 'Auto-saves: {{c}} {{n}}/mo', noGoals: 'No goals', startNow: 'Create your first savings goal', deposit: 'Deposit', addDeposit: 'Add a deposit', chooseTemplate: 'Choose a template', newProject: 'New project', customProject: 'Custom project', goalCompleted: '🎉 Goal reached!', autoMonthly: '{{c}} {{n}}/mo auto', reachedOn: 'Reached on {{d}}', monthsLeft: 'in {{n}} months', objective: 'Target', alreadySaved: 'Already saved', autoMonth: 'Auto/month', deadline: 'Deadline', color: 'Color', createProject: 'Create project', myProject: 'My project', errMissing: 'Please fill the title and target' },
    de: { title: 'Sparen', total: 'Gesamt gespart', target: 'von {{n}} Ziel', addGoal: 'Neues Ziel', remaining: '{{n}} fehlt · {{p}}% erreicht', achieved: '✨ Super! Sie haben {{c}} {{n}} gespart', autoSave: 'Auto-Sparen: {{c}} {{n}}/Mt.', noGoals: 'Keine Ziele', startNow: 'Erstellen Sie Ihr erstes Sparziel', deposit: 'Einzahlen', addDeposit: 'Einzahlung hinzufügen', chooseTemplate: 'Vorlage wählen', newProject: 'Neues Projekt', customProject: 'Eigenes Projekt', goalCompleted: '🎉 Ziel erreicht!', autoMonthly: '{{c}} {{n}}/Mt. auto', reachedOn: 'Erreicht am {{d}}', monthsLeft: 'in {{n}} Monaten', objective: 'Ziel', alreadySaved: 'Bereits gespart', autoMonth: 'Auto/Monat', deadline: 'Frist', color: 'Farbe', createProject: 'Projekt erstellen', myProject: 'Mein Projekt', errMissing: 'Bitte Titel und Ziel angeben' },
    it: { title: 'Risparmi', total: 'Capitale risparmiato', target: 'su {{n}} obiettivo', addGoal: 'Nuovo obiettivo', remaining: '{{n}} mancano · {{p}}% raggiunto', achieved: '✨ Bravo! Hai risparmiato {{c}} {{n}}', autoSave: 'Risparmi auto: {{c}} {{n}}/mese', noGoals: 'Nessun obiettivo', startNow: 'Crea il tuo primo obiettivo di risparmio', deposit: 'Deposita', addDeposit: 'Aggiungi versamento', chooseTemplate: 'Scegli un modello', newProject: 'Nuovo progetto', customProject: 'Progetto personalizzato', goalCompleted: '🎉 Obiettivo raggiunto!', autoMonthly: '{{c}} {{n}}/mese auto', reachedOn: 'Raggiunto il {{d}}', monthsLeft: 'tra {{n}} mesi', objective: 'Obiettivo', alreadySaved: 'Già risparmiato', autoMonth: 'Auto/mese', deadline: 'Scadenza', color: 'Colore', createProject: 'Crea progetto', myProject: 'Il mio progetto', errMissing: 'Inserisci titolo e obiettivo' },
  },

  // ─────────── Expenses ───────────
  expenses: {
    fr: { title: 'Dépenses', daily: 'Quotidien', pro: 'Pro', contracts: 'Contrats', noTx: 'Aucune dépense', noPro: 'Aucun frais pro', noContracts: 'Aucun contrat', addExpense: 'Ajouter une dépense', addProSub: 'Ajoutez vos frais professionnels pour les exporter en PDF', addDailySub: 'Commencez par ajouter vos dépenses quotidiennes', addContractsSub: 'Ajoutez vos contrats pour suivre les renouvellements', summaryDaily: 'Total dépenses', summaryPro: 'Frais professionnels', summaryContracts: 'Contrats actifs', proLockedTitle: 'Fonctionnalité Pro', proLockedText: 'Passez à Budgy Pro pour gérer vos frais professionnels et exporter des notes de frais PDF.', newExpense: 'Nouvelle dépense', newProExpense: 'Nouveau frais pro', justification: 'Justification', exJustif: 'ex: Réunion client', exTitle: 'ex: Migros', expiresOn: 'Expire le {{d}}', urgent: 'Urgent', deleteTitle: 'Supprimer', deleteMsg: 'Êtes-vous sûr de vouloir supprimer cette dépense ?' },
    en: { title: 'Expenses', daily: 'Daily', pro: 'Business', contracts: 'Contracts', noTx: 'No expenses', noPro: 'No business expenses', noContracts: 'No contracts', addExpense: 'Add expense', addProSub: 'Add business expenses to export them as PDF', addDailySub: 'Start by adding your daily expenses', addContractsSub: 'Add contracts to track renewals', summaryDaily: 'Total expenses', summaryPro: 'Business expenses', summaryContracts: 'Active contracts', proLockedTitle: 'Pro feature', proLockedText: 'Upgrade to Budgy Pro to manage business expenses and export PDF reports.', newExpense: 'New expense', newProExpense: 'New business expense', justification: 'Justification', exJustif: 'e.g. Client meeting', exTitle: 'e.g. Migros', expiresOn: 'Expires on {{d}}', urgent: 'Urgent', deleteTitle: 'Delete', deleteMsg: 'Are you sure you want to delete this expense?' },
    de: { title: 'Ausgaben', daily: 'Täglich', pro: 'Geschäftlich', contracts: 'Verträge', noTx: 'Keine Ausgaben', noPro: 'Keine Geschäftsausgaben', noContracts: 'Keine Verträge', addExpense: 'Ausgabe hinzufügen', addProSub: 'Geschäftsausgaben hinzufügen, um sie als PDF zu exportieren', addDailySub: 'Beginnen Sie mit Ihren täglichen Ausgaben', addContractsSub: 'Verträge hinzufügen, um Verlängerungen zu verfolgen', summaryDaily: 'Ausgaben gesamt', summaryPro: 'Geschäftsausgaben', summaryContracts: 'Aktive Verträge', proLockedTitle: 'Pro-Funktion', proLockedText: 'Upgraden Sie auf Budgy Pro, um Geschäftsausgaben zu verwalten und PDFs zu exportieren.', newExpense: 'Neue Ausgabe', newProExpense: 'Neue Geschäftsausgabe', justification: 'Begründung', exJustif: 'z. B. Kundenmeeting', exTitle: 'z. B. Migros', expiresOn: 'Läuft ab am {{d}}', urgent: 'Dringend', deleteTitle: 'Löschen', deleteMsg: 'Möchten Sie diese Ausgabe wirklich löschen?' },
    it: { title: 'Spese', daily: 'Quotidiane', pro: 'Lavoro', contracts: 'Contratti', noTx: 'Nessuna spesa', noPro: 'Nessuna spesa lavorativa', noContracts: 'Nessun contratto', addExpense: 'Aggiungi spesa', addProSub: 'Aggiungi spese di lavoro per esportarle in PDF', addDailySub: 'Inizia aggiungendo le tue spese quotidiane', addContractsSub: 'Aggiungi contratti per monitorare i rinnovi', summaryDaily: 'Totale spese', summaryPro: 'Spese di lavoro', summaryContracts: 'Contratti attivi', proLockedTitle: 'Funzione Pro', proLockedText: 'Passa a Budgy Pro per gestire le spese di lavoro ed esportare PDF.', newExpense: 'Nuova spesa', newProExpense: 'Nuova spesa di lavoro', justification: 'Giustificativo', exJustif: 'es. Riunione cliente', exTitle: 'es. Migros', expiresOn: 'Scade il {{d}}', urgent: 'Urgente', deleteTitle: 'Elimina', deleteMsg: 'Sei sicuro di voler eliminare questa spesa?' },
  },

  // ─────────── More menu ───────────
  more: {
    fr: { title: 'Plus', upgrade: 'Passer à Budgy Pro', upgradeSub: 'IA illimitée · Tax · Export · Cloud — 7 jours gratuits', trialActive: 'Essai gratuit actif · {{n}} jours restants', subscribe: 'S\'abonner', sectionAI: 'IA', sectionFinance: '💰 Finances', sectionDocuments: 'Documents', sectionShare: 'Partage', sectionSecurity: 'Sécurité', sectionTools: '🛠️ Outils', sectionAccount: '👤 Compte', sectionSettings: 'Paramètres', incomes: 'Mes revenus', incomesSub: 'Salaire · 13ème · Bonus · Locations', budgets: 'Budgets', budgetsSub: 'Enveloppes mensuelles', recurring: 'Charges récurrentes', recurringSub: 'Frais & abonnements', investments: 'Investissements', debts: 'Dettes', invoices: 'Factures', invoicesSub: 'QR-bills · paiements', lamal: 'LAMal & Subsides', lamalSub: '26 cantons · 15 assureurs', aiOptimizer: 'Économiseur IA', aiOptimizerSub: 'Trouve des économies concrètes', predict: 'Coach Predict', predictSub: 'Prédictions & conseils GPT', taxOpt: 'Optimiseur d\'impôts', taxOptSub: 'IFD + ICC', exportPdf: 'Export PDF', emailImport: 'Import email', emailImportSub: 'Import email IA', documents: 'Mon classeur', receipts: 'Tickets & reçus', groups: 'Groupes & amis', groupsSub: 'Dépenses partagées', family: 'Mode famille', security: 'Verrou & biométrie', securitySub: 'PIN · Face ID · panique', cloudSync: 'Sync Cloud', cloudSyncSub: 'Supabase · auto multi-appareils', subscription: 'Budgy Pro', subscriptionTrial: 'Essai · fin {{d}}', subscriptionActive: 'Actif · merci !', subscriptionFree: 'CHF 4.90/mois · 7j d\'essai gratuit', preferences: 'Préférences', preferencesSub: 'Langue · devise · thème', legal: 'Informations légales', legalSub: 'Confidentialité · CGU · Sources', logout: 'Déconnexion', dataPrivate: 'Données chiffrées · Sync privée 🇨🇭' },
    en: { title: 'More', upgrade: 'Upgrade to Budgy Pro', upgradeSub: 'Unlimited AI · Tax · Export · Cloud — 7 days free', trialActive: 'Free trial active · {{n}} days left', subscribe: 'Subscribe', sectionAI: 'AI', sectionFinance: '💰 Finance', sectionDocuments: 'Documents', sectionShare: 'Sharing', sectionSecurity: 'Security', sectionTools: '🛠️ Tools', sectionAccount: '👤 Account', sectionSettings: 'Settings', incomes: 'My income', incomesSub: 'Salary · 13th · Bonus · Rent', budgets: 'Budgets', budgetsSub: 'Monthly envelopes', recurring: 'Recurring charges', recurringSub: 'Fees & subscriptions', investments: 'Investments', debts: 'Debts', invoices: 'Invoices', invoicesSub: 'QR-bills · payments', lamal: 'Health Insurance & Subsidies', lamalSub: '26 cantons · 15 insurers', aiOptimizer: 'AI Money Saver', aiOptimizerSub: 'Find concrete savings', predict: 'Predict Coach', predictSub: 'Predictions & GPT advice', taxOpt: 'Tax Optimizer', taxOptSub: 'Federal + Cantonal tax', exportPdf: 'Export PDF', emailImport: 'Email import', emailImportSub: 'AI email import', documents: 'My binder', receipts: 'Receipts', groups: 'Groups & friends', groupsSub: 'Shared expenses', family: 'Family mode', security: 'Lock & biometrics', securitySub: 'PIN · Face ID · panic', cloudSync: 'Cloud sync', cloudSyncSub: 'Supabase · auto multi-devices', subscription: 'Budgy Pro', subscriptionTrial: 'Trial · ends {{d}}', subscriptionActive: 'Active · thank you!', subscriptionFree: 'CHF 4.90/mo · 7-day free trial', preferences: 'Preferences', preferencesSub: 'Language · currency · theme', legal: 'Legal notices', legalSub: 'Privacy · ToS · Sources', logout: 'Log out', dataPrivate: 'Encrypted data · Private sync 🇨🇭' },
    de: { title: 'Mehr', upgrade: 'Auf Budgy Pro upgraden', upgradeSub: 'Unbegrenzt KI · Steuer · Export · Cloud — 7 Tage gratis', trialActive: 'Testphase aktiv · noch {{n}} Tage', subscribe: 'Abonnieren', sectionAI: 'KI', sectionFinance: '💰 Finanzen', sectionDocuments: 'Dokumente', sectionShare: 'Teilen', sectionSecurity: 'Sicherheit', sectionTools: '🛠️ Werkzeuge', sectionAccount: '👤 Konto', sectionSettings: 'Einstellungen', incomes: 'Mein Einkommen', incomesSub: 'Lohn · 13. · Bonus · Miete', budgets: 'Budgets', budgetsSub: 'Monatliche Umschläge', recurring: 'Wiederkehrende Kosten', recurringSub: 'Gebühren & Abos', investments: 'Investments', debts: 'Schulden', invoices: 'Rechnungen', invoicesSub: 'QR-Rechnungen · Zahlungen', lamal: 'Krankenkasse & Prämienverbilligung', lamalSub: '26 Kantone · 15 Versicherer', aiOptimizer: 'KI-Sparassistent', aiOptimizerSub: 'Findet konkrete Einsparungen', predict: 'Predict Coach', predictSub: 'Vorhersagen & GPT-Tipps', taxOpt: 'Steueroptimierer', taxOptSub: 'Bund + Kanton', exportPdf: 'PDF-Export', emailImport: 'E-Mail-Import', emailImportSub: 'KI E-Mail-Import', documents: 'Mein Ordner', receipts: 'Belege', groups: 'Gruppen & Freunde', groupsSub: 'Geteilte Ausgaben', family: 'Familienmodus', security: 'Sperre & Biometrie', securitySub: 'PIN · Face ID · Panik', cloudSync: 'Cloud-Sync', cloudSyncSub: 'Supabase · auto Multi-Geräte', subscription: 'Budgy Pro', subscriptionTrial: 'Test · endet {{d}}', subscriptionActive: 'Aktiv · danke!', subscriptionFree: 'CHF 4.90/Mt. · 7 Tage gratis testen', preferences: 'Einstellungen', preferencesSub: 'Sprache · Währung · Design', legal: 'Rechtliche Hinweise', legalSub: 'Datenschutz · AGB · Quellen', logout: 'Abmelden', dataPrivate: 'Verschlüsselte Daten · Privater Sync 🇨🇭' },
    it: { title: 'Altro', upgrade: 'Passa a Budgy Pro', upgradeSub: 'IA illimitata · Tasse · Export · Cloud — 7 giorni gratis', trialActive: 'Prova gratuita attiva · {{n}} giorni rimanenti', subscribe: 'Abbonati', sectionAI: 'IA', sectionFinance: '💰 Finanze', sectionDocuments: 'Documenti', sectionShare: 'Condivisione', sectionSecurity: 'Sicurezza', sectionTools: '🛠️ Strumenti', sectionAccount: '👤 Account', sectionSettings: 'Impostazioni', incomes: 'I miei redditi', incomesSub: 'Stipendio · 13ma · Bonus · Affitti', budgets: 'Budget', budgetsSub: 'Buste mensili', recurring: 'Spese ricorrenti', recurringSub: 'Costi & abbonamenti', investments: 'Investimenti', debts: 'Debiti', invoices: 'Fatture', invoicesSub: 'QR-bill · pagamenti', lamal: 'Assicurazione malattia & Sussidi', lamalSub: '26 cantoni · 15 assicuratori', aiOptimizer: 'Risparmiatore IA', aiOptimizerSub: 'Trova risparmi concreti', predict: 'Coach Predict', predictSub: 'Previsioni & consigli GPT', taxOpt: 'Ottimizzatore tasse', taxOptSub: 'Federali + Cantonali', exportPdf: 'Export PDF', emailImport: 'Importa email', emailImportSub: 'Importa email IA', documents: 'Il mio classificatore', receipts: 'Scontrini', groups: 'Gruppi & amici', groupsSub: 'Spese condivise', family: 'Modalità famiglia', security: 'Blocco & biometria', securitySub: 'PIN · Face ID · panico', cloudSync: 'Sync Cloud', cloudSyncSub: 'Supabase · auto multi-dispositivi', subscription: 'Budgy Pro', subscriptionTrial: 'Prova · fine {{d}}', subscriptionActive: 'Attivo · grazie!', subscriptionFree: 'CHF 4.90/mese · 7 giorni gratis', preferences: 'Preferenze', preferencesSub: 'Lingua · valuta · tema', legal: 'Note legali', legalSub: 'Privacy · ToS · Fonti', logout: 'Disconnetti', dataPrivate: 'Dati cifrati · Sync privato 🇨🇭' },
  },

  // ─────────── Settings ───────────
  settings: {
    fr: { title: 'Paramètres', language: 'Langue', currency: 'Devise', theme: 'Thème', appearance: 'Apparence', dark: 'Sombre', light: 'Clair', auto: 'Auto', themeHint: '"Auto" suit automatiquement le thème de votre appareil.', dataSection: 'Données', backup: 'Sauvegarde', backupValue: 'Temps réel · local', servers: 'Serveurs', serversValue: 'Aucun · 100% privé', version: 'Version', appStoreReady: 'App Store Ready', security: 'Sécurité', dataPrivacy: 'Données & confidentialité', clearData: 'Supprimer mes données', logout: 'Déconnexion', dangerZone: '⚠️ Zone dangereuse', dangerText: 'Supprime toutes vos données localement. Irréversible.', clearConfirmTitle: 'Tout supprimer ?', clearConfirm: 'Toutes vos données seront supprimées. Continuer ?', logoutConfirmTitle: 'Déconnexion', logoutConfirm: 'Voulez-vous vous déconnecter ?', currencyConverted: 'Tous les montants sont convertis en {{c}}', example: 'ex' },
    en: { title: 'Settings', language: 'Language', currency: 'Currency', theme: 'Theme', appearance: 'Appearance', dark: 'Dark', light: 'Light', auto: 'Auto', themeHint: '"Auto" follows your device theme automatically.', dataSection: 'Data', backup: 'Backup', backupValue: 'Real-time · local', servers: 'Servers', serversValue: 'None · 100% private', version: 'Version', appStoreReady: 'App Store Ready', security: 'Security', dataPrivacy: 'Data & privacy', clearData: 'Delete my data', logout: 'Log out', dangerZone: '⚠️ Danger zone', dangerText: 'Permanently deletes all your local data. Irreversible.', clearConfirmTitle: 'Delete everything?', clearConfirm: 'All your data will be deleted. Continue?', logoutConfirmTitle: 'Log out', logoutConfirm: 'Do you want to log out?', currencyConverted: 'All amounts are converted to {{c}}', example: 'e.g.' },
    de: { title: 'Einstellungen', language: 'Sprache', currency: 'Währung', theme: 'Design', appearance: 'Erscheinungsbild', dark: 'Dunkel', light: 'Hell', auto: 'Auto', themeHint: '"Auto" folgt automatisch dem Geräte-Design.', dataSection: 'Daten', backup: 'Sicherung', backupValue: 'Echtzeit · lokal', servers: 'Server', serversValue: 'Keine · 100% privat', version: 'Version', appStoreReady: 'App Store bereit', security: 'Sicherheit', dataPrivacy: 'Daten & Privatsphäre', clearData: 'Meine Daten löschen', logout: 'Abmelden', dangerZone: '⚠️ Gefahrenzone', dangerText: 'Löscht alle lokalen Daten unwiderruflich.', clearConfirmTitle: 'Alles löschen?', clearConfirm: 'Alle Ihre Daten werden gelöscht. Fortfahren?', logoutConfirmTitle: 'Abmelden', logoutConfirm: 'Möchten Sie sich abmelden?', currencyConverted: 'Alle Beträge werden in {{c}} umgerechnet', example: 'z.B.' },
    it: { title: 'Impostazioni', language: 'Lingua', currency: 'Valuta', theme: 'Tema', appearance: 'Aspetto', dark: 'Scuro', light: 'Chiaro', auto: 'Auto', themeHint: '"Auto" segue automaticamente il tema del dispositivo.', dataSection: 'Dati', backup: 'Backup', backupValue: 'Tempo reale · locale', servers: 'Server', serversValue: 'Nessuno · 100% privato', version: 'Versione', appStoreReady: 'Pronto per App Store', security: 'Sicurezza', dataPrivacy: 'Dati & privacy', clearData: 'Cancella i miei dati', logout: 'Disconnetti', dangerZone: '⚠️ Zona pericolosa', dangerText: 'Elimina tutti i dati locali. Irreversibile.', clearConfirmTitle: 'Cancellare tutto?', clearConfirm: 'Tutti i tuoi dati saranno eliminati. Continuare?', logoutConfirmTitle: 'Disconnetti', logoutConfirm: 'Vuoi disconnetterti?', currencyConverted: 'Tutti gli importi sono convertiti in {{c}}', example: 'es.' },
  },

  // ─────────── Paywall ───────────
  paywall: {
    fr: { title: 'Prenez le contrôle total de votre argent', subtitle: 'Budgy vous aide à économiser, prévoir et optimiser vos finances.', tryFree: 'Essayer gratuitement 7 jours', subDirect: 'ou s\'abonner directement', monthly: 'Mensuel', annual: 'Annuel', bestOffer: 'MEILLEURE OFFRE', noCommit: 'Sans engagement', cancelAny: 'Annulation à tout moment', securePay: 'Paiement sécurisé', restore: 'Restaurer' },
    en: { title: 'Take full control of your money', subtitle: 'Budgy helps you save, forecast and optimize your finances.', tryFree: 'Try free for 7 days', subDirect: 'or subscribe directly', monthly: 'Monthly', annual: 'Annual', bestOffer: 'BEST OFFER', noCommit: 'No commitment', cancelAny: 'Cancel anytime', securePay: 'Secure payment', restore: 'Restore' },
    de: { title: 'Übernehmen Sie die Kontrolle über Ihr Geld', subtitle: 'Budgy hilft Ihnen zu sparen, vorauszuplanen und Ihre Finanzen zu optimieren.', tryFree: '7 Tage kostenlos testen', subDirect: 'oder direkt abonnieren', monthly: 'Monatlich', annual: 'Jährlich', bestOffer: 'BESTES ANGEBOT', noCommit: 'Keine Bindung', cancelAny: 'Jederzeit kündbar', securePay: 'Sichere Zahlung', restore: 'Wiederherstellen' },
    it: { title: 'Prendi il controllo totale del tuo denaro', subtitle: 'Budgy ti aiuta a risparmiare, prevedere e ottimizzare le tue finanze.', tryFree: 'Prova gratis per 7 giorni', subDirect: 'o abbonati direttamente', monthly: 'Mensile', annual: 'Annuale', bestOffer: 'MIGLIORE OFFERTA', noCommit: 'Senza impegno', cancelAny: 'Annulla in qualsiasi momento', securePay: 'Pagamento sicuro', restore: 'Ripristina' },
  },

  // ─────────── Auth ───────────
  auth: {
    fr: { tagline: 'Vos finances, en toute sérénité 🇨🇭', login: 'Connexion', signup: 'Créer un compte', email: 'Email', password: 'Mot de passe', name: 'Prénom', loginCta: 'Se connecter', signupCta: 'Créer mon compte', noAccount: 'Pas encore de compte ?', haveAccount: 'Déjà un compte ?', forgotPwd: 'Mot de passe oublié ?', demoMode: 'Essayer en mode démo (Pro activé)', or: 'OU', emailPlaceholder: 'email@exemple.ch', passwordPlaceholder: 'Min. 6 caractères', namePlaceholder: 'Votre prénom', errEmail: 'Email invalide', errPassword: 'Mot de passe trop court', errName: 'Prénom requis' },
    en: { tagline: 'Your finances, in total peace of mind 🇨🇭', login: 'Sign in', signup: 'Sign up', email: 'Email', password: 'Password', name: 'First name', loginCta: 'Sign in', signupCta: 'Create account', noAccount: 'No account yet?', haveAccount: 'Already have an account?', forgotPwd: 'Forgot password?', demoMode: 'Try in demo mode (Pro enabled)', or: 'OR', emailPlaceholder: 'email@example.com', passwordPlaceholder: 'Min. 6 characters', namePlaceholder: 'Your first name', errEmail: 'Invalid email', errPassword: 'Password too short', errName: 'Name required' },
    de: { tagline: 'Ihre Finanzen, in vollkommener Ruhe 🇨🇭', login: 'Anmelden', signup: 'Konto erstellen', email: 'E-Mail', password: 'Passwort', name: 'Vorname', loginCta: 'Anmelden', signupCta: 'Konto erstellen', noAccount: 'Noch kein Konto?', haveAccount: 'Schon ein Konto?', forgotPwd: 'Passwort vergessen?', demoMode: 'Demo-Modus testen (Pro aktiv)', or: 'ODER', emailPlaceholder: 'email@beispiel.ch', passwordPlaceholder: 'Min. 6 Zeichen', namePlaceholder: 'Ihr Vorname', errEmail: 'Ungültige E-Mail', errPassword: 'Passwort zu kurz', errName: 'Vorname erforderlich' },
    it: { tagline: 'Le tue finanze, in totale tranquillità 🇨🇭', login: 'Accedi', signup: 'Registrati', email: 'Email', password: 'Password', name: 'Nome', loginCta: 'Accedi', signupCta: 'Crea account', noAccount: 'Non hai ancora un account?', haveAccount: 'Hai già un account?', forgotPwd: 'Password dimenticata?', demoMode: 'Prova in modalità demo (Pro attivo)', or: 'O', emailPlaceholder: 'email@esempio.ch', passwordPlaceholder: 'Min. 6 caratteri', namePlaceholder: 'Il tuo nome', errEmail: 'Email non valida', errPassword: 'Password troppo corta', errName: 'Nome richiesto' },
  },

  // ─────────── LAMal Comparator ───────────
  lamal: {
    fr: { title: 'Comparateur LAMal', subtitle: 'Priminfo 2026 · OFSP/BAG', dataSource: 'Données officielles Priminfo 2026', bestOffer: 'Meilleure offre · {{c}}', perMonth: 'CHF/mois', min: 'Min', avg: 'Moyenne', max: 'Max', vsLast: '{{p}}% vs 2025', avgCh: 'CH: {{n}}/mois', subsidyBadge: 'Subside: -{{n}} CHF/mois', insurers: 'Assureurs', optimize: 'Optimiser', subsidy: 'Subsides', ranking: '26 cantons', topInsurers: 'Top {{n}} assureurs · {{c}}', franchiseLabel: 'Franchise CHF {{n}} · {{m}}', savingsVs: 'Économie: CHF {{n}}/an vs moyenne', annualPerYear: '{{n}}/an', noteText: 'Estimations basées sur les indices Priminfo 2026 et la dispersion réelle observée par canton. Le rang varie selon votre canton, votre âge et votre franchise.', age: 'Âge', child: 'Enfant', young: 'Jeune ({{n}})', adultYears: '{{n}} ans', franchise: 'Franchise', model: 'Modèle', optimizeFranchise: 'Optimisation franchise', goodHealth: 'Bonne santé', chronic: 'Maladie chronique', maxCoverage: 'Couverture maximale', savingPerYear: 'Économie: ~{{n}}/an', importantDates: 'Dates importantes', date1: '30 novembre: dernier délai de résiliation', date2: 'Résiliation par lettre recommandée', date3: 'Changement gratuit et sans justification', date4: 'Aucune différence de prestations (assurance de base)', subsidyTitle: 'Réduction de primes', annualIncome: 'Revenu annuel', single: 'Célibataire', married: 'Marié(e)', childrenLabel: 'Enfants', eligible: 'Éligible aux subsides', notEligible: 'Non éligible', subsidyMonth: '-CHF {{n}}/mois', subsidyYear: 'Économie: CHF {{n}}/an', cantonsTitle: '26 cantons · Prime moyenne 2026', cheapestInsurer: 'Le moins cher dans votre canton' },
    en: { title: 'Health insurance compare', subtitle: 'Priminfo 2026 · FOPH/BAG', dataSource: 'Official Priminfo 2026 data', bestOffer: 'Best offer · {{c}}', perMonth: 'CHF/mo', min: 'Min', avg: 'Average', max: 'Max', vsLast: '{{p}}% vs 2025', avgCh: 'CH: {{n}}/mo', subsidyBadge: 'Subsidy: -{{n}} CHF/mo', insurers: 'Insurers', optimize: 'Optimize', subsidy: 'Subsidy', ranking: '26 cantons', topInsurers: 'Top {{n}} insurers · {{c}}', franchiseLabel: 'Excess CHF {{n}} · {{m}}', savingsVs: 'Save: CHF {{n}}/yr vs average', annualPerYear: '{{n}}/yr', noteText: 'Estimates based on Priminfo 2026 indices and real per-canton dispersion. Ranking varies by canton, age and excess.', age: 'Age', child: 'Child', young: 'Young ({{n}})', adultYears: '{{n}} years', franchise: 'Excess', model: 'Model', optimizeFranchise: 'Excess optimisation', goodHealth: 'Good health', chronic: 'Chronic illness', maxCoverage: 'Maximum coverage', savingPerYear: 'Save: ~{{n}}/yr', importantDates: 'Key dates', date1: 'Nov 30: termination deadline', date2: 'Termination by registered letter', date3: 'Free switch, no justification needed', date4: 'No difference in benefits (basic plan)', subsidyTitle: 'Premium reduction', annualIncome: 'Annual income', single: 'Single', married: 'Married', childrenLabel: 'Children', eligible: 'Eligible for subsidy', notEligible: 'Not eligible', subsidyMonth: '-CHF {{n}}/mo', subsidyYear: 'Save: CHF {{n}}/yr', cantonsTitle: '26 cantons · 2026 avg premium', cheapestInsurer: 'Cheapest in your canton' },
    de: { title: 'Krankenkassen-Vergleich', subtitle: 'Priminfo 2026 · BAG', dataSource: 'Offizielle Priminfo 2026 Daten', bestOffer: 'Bestes Angebot · {{c}}', perMonth: 'CHF/Mt.', min: 'Min', avg: 'Durchschnitt', max: 'Max', vsLast: '{{p}}% vs 2025', avgCh: 'CH: {{n}}/Mt.', subsidyBadge: 'Verbilligung: -{{n}} CHF/Mt.', insurers: 'Versicherer', optimize: 'Optimieren', subsidy: 'Verbilligung', ranking: '26 Kantone', topInsurers: 'Top {{n}} Versicherer · {{c}}', franchiseLabel: 'Franchise CHF {{n}} · {{m}}', savingsVs: 'Ersparnis: CHF {{n}}/J. vs Durchschnitt', annualPerYear: '{{n}}/J.', noteText: 'Schätzungen basierend auf den Priminfo 2026 Indizes und der realen kantonalen Streuung. Rang variiert je nach Kanton, Alter und Franchise.', age: 'Alter', child: 'Kind', young: 'Jung ({{n}})', adultYears: '{{n}} Jahre', franchise: 'Franchise', model: 'Modell', optimizeFranchise: 'Franchisen-Optimierung', goodHealth: 'Gesund', chronic: 'Chronisch krank', maxCoverage: 'Maximale Deckung', savingPerYear: 'Ersparnis: ~{{n}}/J.', importantDates: 'Wichtige Daten', date1: '30. November: Kündigungsfrist', date2: 'Kündigung per Einschreiben', date3: 'Kostenloser Wechsel, ohne Begründung', date4: 'Gleiche Leistungen (Grundversicherung)', subsidyTitle: 'Prämienverbilligung', annualIncome: 'Jahreseinkommen', single: 'Single', married: 'Verheiratet', childrenLabel: 'Kinder', eligible: 'Anspruch auf Verbilligung', notEligible: 'Kein Anspruch', subsidyMonth: '-CHF {{n}}/Mt.', subsidyYear: 'Ersparnis: CHF {{n}}/J.', cantonsTitle: '26 Kantone · Ø Prämie 2026', cheapestInsurer: 'Günstigster in Ihrem Kanton' },
    it: { title: 'Comparatore LAMal', subtitle: 'Priminfo 2026 · UFSP/BAG', dataSource: 'Dati ufficiali Priminfo 2026', bestOffer: 'Miglior offerta · {{c}}', perMonth: 'CHF/mese', min: 'Min', avg: 'Media', max: 'Max', vsLast: '{{p}}% vs 2025', avgCh: 'CH: {{n}}/mese', subsidyBadge: 'Sussidio: -{{n}} CHF/mese', insurers: 'Assicuratori', optimize: 'Ottimizza', subsidy: 'Sussidi', ranking: '26 cantoni', topInsurers: 'Top {{n}} assicuratori · {{c}}', franchiseLabel: 'Franchigia CHF {{n}} · {{m}}', savingsVs: 'Risparmio: CHF {{n}}/anno vs media', annualPerYear: '{{n}}/anno', noteText: 'Stime basate sugli indici Priminfo 2026 e sulla dispersione reale per cantone. La classifica varia in base a cantone, età e franchigia.', age: 'Età', child: 'Bambino', young: 'Giovane ({{n}})', adultYears: '{{n}} anni', franchise: 'Franchigia', model: 'Modello', optimizeFranchise: 'Ottimizzazione franchigia', goodHealth: 'Buona salute', chronic: 'Malattia cronica', maxCoverage: 'Copertura massima', savingPerYear: 'Risparmio: ~{{n}}/anno', importantDates: 'Date importanti', date1: '30 novembre: termine di disdetta', date2: 'Disdetta per lettera raccomandata', date3: 'Cambio gratuito e senza giustificazione', date4: 'Nessuna differenza di prestazioni (di base)', subsidyTitle: 'Riduzione del premio', annualIncome: 'Reddito annuo', single: 'Single', married: 'Sposato/a', childrenLabel: 'Figli', eligible: 'Idoneo al sussidio', notEligible: 'Non idoneo', subsidyMonth: '-CHF {{n}}/mese', subsidyYear: 'Risparmio: CHF {{n}}/anno', cantonsTitle: '26 cantoni · Premio medio 2026', cheapestInsurer: 'Il più economico nel tuo cantone' },
  },
} as const;

// Helper for parameterized strings: t('savings.target', { n: 1000 })
export function interpolate(template: string, params?: Record<string, any>): string {
  if (!params) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => String(params[key] ?? ''));
}
